# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ExperimentalDesign": "00_core.ipynb",
         "random_design": "01_randomdesign.ipynb",
         "fullfactorial": "02_fullfactorial.ipynb",
         "fullfactorial2k": "02_fullfactorial.ipynb"}

modules = ["core.py",
           "randomdesign.py",
           "fullfactorial.py"]

doc_url = "https://Newton314.github.io/fastDOE/"

git_url = "https://github.com/Newton314/fastDOE/tree/master/"

def custom_doc_links(name): return None
