# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['ExperimentalDesign']

# %% ../00_core.ipynb 4
import numpy as np
import pandas as pd

# %% ../00_core.ipynb 5
class ExperimentalDesign():
    def __init__(self, design: pd.DataFrame, factors: list, level_values: list):
        self.design: pd.DataFrame = design
        self.matrix: np.ndarray = design.query("rep==0")[factors].values
        self.lvl_values: list = level_values
    
    def __repr__(self):
        return f"{self.design}"
